language: python
sudo: required
python:
- '3.5'
services:
- mysql
env:
  - DJANGO_VERSION=1.9.5 DB=mysql
#branchs:
#  only:
#  - master
install:
- pip install -r requirements.txt
- mv configs.example.json configs.json
before_script:
- mysql -e "create database IF NOT EXISTS wechat_ticket;"
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
