language: python
sudo: required
python:
- '3.5'
services:
- mysql
env:
- DJANGO=1.9.5 DB=mysql
  global:
    - BUILD_ON_TRAVIS=true
branchs:
  only:
  - master
install:
- pip install -r requirements.txt
before_script:
- mysql -e "create database wechat_ticket;" -uroot
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
