sudo: required
language: python
python:
- '3.5'
services:
- mysql
env:
- DJANGO=1.9.5 DB=mysql
branchs:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_80add9e7e319_key -iv $encrypted_80add9e7e319_iv -in configs.json.enc -out configs.json -d
install:
- pip install -r requirements.txt
before_script:
- sudo mysql -e "create database wechat_ticket;"
- sudo python3 manage.py makemigrations
- sudo python3 manage.py migrate
script:
- sudo python3 manage.py test
